# Generated by Django 4.0.2 on 2022-02-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zomatoDemoAdmin', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
                ('order_placed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(related_name='cart_dishes', to='zomatoDemoCustomer.Cart')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zomatoDemoAdmin.restaurants')),
            ],
        ),
    ]
