# Generated by Django 4.0.2 on 2022-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoDemoAdmin', '0002_initial'),
        ('zomatoDemoCustomer', '0004_remove_orders_order_dishes_orders_ordered_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_dishes',
            field=models.ManyToManyField(through='zomatoDemoCustomer.Cart', to='zomatoDemoAdmin.Dishes'),
        ),
    ]
