# Generated by Django 4.0.2 on 2022-02-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoDemoCustomer', '0005_alter_orders_ordered_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ordered_dishes',
            new_name='order_dishes',
        ),
    ]
