# Generated by Django 4.0.2 on 2022-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoDemoAdmin', '0002_initial'),
        ('zomatoDemoCustomer', '0006_rename_ordered_dishes_orders_order_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_dishes',
        ),
        migrations.AddField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='zomatoDemoAdmin.Dishes'),
        ),
    ]
