# Generated by Django 4.0.2 on 2022-02-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomatoDemoCustomer', '0007_remove_orders_order_dishes_orders_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='zomatoDemoCustomer.Cart'),
        ),
    ]
