# Generated by Django 4.0.2 on 2022-02-27 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zomatoDemoAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishes',
            name='available_in',
            field=models.ManyToManyField(related_name='restaurant_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
